In [5]:
import numpy as np

# **Basic array creation**

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

2 d array

In [7]:
l=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **Array genearation func**

** arrange -> range of array**



In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

**linspace -> return evenly spaced no. over a sspecified interval**

In [11]:
np.linspace(1,5,3)

array([1., 3., 5.])

# **Random generation function**

normalised value only -> concept of stadardization (-3 se 3)

In [12]:
# return vector
np.random.rand(10)

array([0.00919637, 0.61513276, 0.54908058, 0.76460586, 0.56036448,
       0.17564302, 0.95951443, 0.36527372, 0.43215399, 0.5932074 ])

In [13]:
np.random.randn(10)

array([ 0.32321981,  0.13775886, -0.94570984, -0.57766584,  2.52917223,
       -0.86675772,  0.81202654, -0.00691168, -0.09654965,  0.73270455])

In [14]:
np.random.randint(10,20,10)

array([12, 18, 15, 15, 13, 19, 15, 11, 13, 10])



```
Attributes -> kind of variable defined in a class
```
```
Methods -> functions defined in a class
-> methods are called
```

# **Array Attribute**

In [15]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr.shape

(3, 3)

In [17]:
arr.size

9

In [18]:
arr.dtype

dtype('int64')

# **Array Methods**

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr.min()

np.int64(1)

In [21]:
arr.max()

np.int64(9)

In [22]:
arr.sum()

np.int64(45)

In [23]:
# axis = 0 column wise
np.sum(arr,axis=0)

array([12, 15, 18])

In [24]:
np.sum(arr,axis =1)

array([ 6, 15, 24])

In [25]:
arr.mean()

np.float64(5.0)

In [26]:
arr.std()

np.float64(2.581988897471611)

In [27]:
arr.argmax()

np.int64(8)

In [28]:
arr.argmin()

np.int64(0)

# **Reshaping & Resizing**

In [29]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [30]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# **NUMPY indexing & Slicing of vectors**

In [31]:
import numpy as np

In [32]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
arr[7]

np.int64(18)

In [34]:
arr[1:5]

array([12, 13, 14, 15])

In [35]:
arr[3::2]

array([14, 16, 18, 20])

# **Indexing of matrix**

In [36]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
arr[0,0]

np.int64(1)

In [38]:
arr[0,4]

np.int64(5)

# **Slicing of matrix**

In [39]:
slice = arr[0:3,1:4]
slice

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [40]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [41]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

# **Bollean indexing**

In [42]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
bool_index = arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [44]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

# **Array Operations**





**1.   Arithmetic operations**



In [45]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [46]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [47]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [48]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [49]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [50]:
a1 // a2

array([0, 0, 0, 0, 0])

In [51]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# **Broadcasting**

In [52]:
l=[10,20,30,40]
arr = np.array(l)

In [53]:
for i in l :
  print(i+10)

20
30
40
50


In [54]:
arr+10

array([20, 30, 40, 50])

In [55]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

# **Deep and shallow copy**

In [57]:
a = np.arange(1,21) # vector
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
slice = a[:5]
slice = slice * 10 # broadcasting
slice

array([10, 20, 30, 40, 50])

# **Concept of swallow copy**
```
whenever you are slicing a portion of an array - it creates a new location to store in RAM
```
whereas in list base list changes


# **Concept of deep copy**
```
when we slice a array -> changes in slice array -> changes in main array
```



In [59]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
b=a
b[0]= 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [61]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**a.copy() # no changes in main array** -> only in b

In [62]:
b= a.copy()
b[0]=100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [63]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# **Matrix operation**

In [64]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [65]:
A

array([[1, 2],
       [3, 4]])

In [66]:
B

array([[5, 6],
       [7, 8]])

Matrix multiplication

In [67]:
A @ B

array([[19, 22],
       [43, 50]])

In [68]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

Array transpose

In [69]:
A.T

array([[1, 3],
       [2, 4]])

# **Advance array manipulation**

**Stacking Array**
```
we cannot stack 2 arrays or matrix
```

In [70]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

vertical stack

In [71]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

horizontal stack

In [72]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [74]:
np.stack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

**Spliting Array**

In [75]:
c= np.arange(0,16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

horizontal split

In [76]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

vertical split

In [77]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# **EXERCISE**

check valid Sudoku

In [78]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],

    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [79]:
import numpy as np

In [80]:
s.sum()

np.int64(405)

In [81]:
b = np.sum(s,axis=1) # rows
b[b==45]

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [82]:
for i in b :
  if i == 45 :
    print("valid")
    break

valid


In [83]:
s[:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [84]:
s[:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [85]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [86]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n= s[i:i+3,j:j+3]
    print(n.sum())

45
45
45
45
45
45
45
45
45


In [87]:
import numpy as np
# col:[Age , math marks , Science marks]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [88]:
data.shape

(5, 3)

In [89]:
# avg age of student
np.mean(data[:,0])

np.float64(18.4)

In [90]:
# extract math marks of all student
data[:,1]

array([85, 92, 76, 65, 90])

In [91]:
# find the highest science marks
np.max(data[:,2])

np.int64(95)

In [92]:
# get the details of student who scored highest in math
data[data[:,1]> 90]

array([[19, 92, 88]])

In [93]:
# Increase math marks of all student by 5
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [94]:
# find how many student are younger than 19
len(data[data[:,0]<19])


3

In [95]:
#calculate the average marks in each subject(column-wise mean)
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [96]:
#get data of student who scored at least 80 in both subjects
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [97]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [98]:
#replace all science marks <75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])